export const articles = [
  // --- Generated Articles (12) ---
  {
    title: "How to Improve Your Skills in League of Legends",
    keyword: "league of legends",
    traffic: "2240000",
    words: 4575,
    createdOn: "20 hours ago",
    category: "Generated Articles",
  },
  {
    title: "The Science of Jungle Pathing in League of Legends",
    keyword: "jungle pathing lol",
    traffic: "1250000",
    words: 3520,
    createdOn: "1 day ago",
    category: "Generated Articles",
  },
  {
    title: "Top 10 Champion Picks for Climbing Ranked",
    keyword: "best champions lol",
    traffic: "1800000",
    words: 2940,
    createdOn: "----",
    category: "Generated Articles",
  },
  {
    title: "How to Improve Map Awareness",
    keyword: "map awareness lol",
    traffic: "960000",
    words: 2650,
    createdOn: "----",
    category: "Generated Articles",
  },
  {
    title: "Solo Queue Mindset Hacks",
    keyword: "league solo queue tips",
    traffic: "820000",
    words: 2330,
    createdOn: "----",
    category: "Generated Articles",
  },
  {
    title: "Best Support Champions to Climb Fast",
    keyword: "support meta lol",
    traffic: "760000",
    words: 2450,
    createdOn: "3 days ago",
    category: "Generated Articles",
  },
  {
    title: "Wave Management Guide",
    keyword: "wave control lol",
    traffic: "540000",
    words: 2890,
    createdOn: "5 days ago",
    category: "Generated Articles",
  },
  {
    title: "Understanding Power Spikes in LoL",
    keyword: "power spikes lol",
    traffic: "610000",
    words: 2510,
    createdOn: "6 days ago",
    category: "Generated Articles",
  },
  {
    title: "Roaming Guide for Mid Laners",
    keyword: "mid lane roam lol",
    traffic: "730000",
    words: 2610,
    createdOn: "7 days ago",
    category: "Generated Articles",
  },
  {
    title: "The Ultimate Guide to Vision Control",
    keyword: "vision control lol",
    traffic: "890000",
    words: 3000,
    createdOn: "8 days ago",
    category: "Generated Articles",
  },
  {
    title: "Best ADCs to Duo with Support",
    keyword: "adc support duo lol",
    traffic: "670000",
    words: 2200,
    createdOn: "9 days ago",
    category: "Generated Articles",
  },
  {
    title: "Climbing with One-Trick Champions",
    keyword: "one trick lol",
    traffic: "710000",
    words: 2600,
    createdOn: "10 days ago",
    category: "Generated Articles",
  },

  // --- Published Articles (10) ---
  {
    title: "How to Master Last Hitting in League of Legends",
    keyword: "league of legends",
    traffic: "2240000",
    words: 3480,
    createdOn: "21 hours ago",
    category: "Published Articles",
  },
  {
    title: "Top Amazon Payment Methods for Quick Access to Funds",
    keyword: "amazon payment methods",
    traffic: "3600",
    words: 2647,
    createdOn: "2 days ago",
    category: "Published Articles",
  },
  {
    title: "Backlinks 101: What are backlinks and why they're important",
    keyword: "backlinks",
    traffic: "800",
    words: 2261,
    createdOn: "3 days ago",
    category: "Published Articles",
  },
  {
    title: "The Rise of Indie Game Developers",
    keyword: "indie games",
    traffic: "2500",
    words: 1800,
    createdOn: "4 days ago",
    category: "Published Articles",
  },
  {
    title: "Best Coding Practices in JavaScript",
    keyword: "javascript best practices",
    traffic: "5000",
    words: 2000,
    createdOn: "----",
    category: "Published Articles",
  },
  {
    title: "UI Design Trends for 2025",
    keyword: "ui trends",
    traffic: "1200",
    words: 1700,
    createdOn: "----",
    category: "Published Articles",
  },
  {
    title: "Beginner's Guide to Web3 Development",
    keyword: "web3 development",
    traffic: "2000",
    words: 2100,
    createdOn: "----",
    category: "Published Articles",
  },
  {
    title: "How to Setup CI/CD for Frontend Projects",
    keyword: "ci/cd frontend",
    traffic: "1800",
    words: 2300,
    createdOn: "5 days ago",
    category: "Published Articles",
  },
  {
    title: "React vs. Vue: Which to Choose in 2025?",
    keyword: "react vs vue",
    traffic: "4500",
    words: 2750,
    createdOn: "6 days ago",
    category: "Published Articles",
  },
  {
    title: "Tailwind CSS: A Beginner's Introduction",
    keyword: "tailwind css intro",
    traffic: "2300",
    words: 1950,
    createdOn: "7 days ago",
    category: "Published Articles",
  },

  // --- Scheduled Articles (9) ---
  {
    title: "7 Tips for Better Teamplay in League of Legends",
    keyword: "league of legends",
    traffic: "2240000",
    words: 2676,
    createdOn: "a day ago",
    category: "Scheduled Articles",
  },
  {
    title: "How to Build a Portfolio Website",
    keyword: "portfolio website",
    traffic: "1500",
    words: 1600,
    createdOn: "6 days ago",
    category: "Scheduled Articles",
  },
  {
    title: "Top SaaS Marketing Tactics in 2024",
    keyword: "saas marketing",
    traffic: "4100",
    words: 3000,
    createdOn: "2 days ago",
    category: "Scheduled Articles",
  },
  {
    title: "Mastering Technical SEO",
    keyword: "technical seo",
    traffic: "2800",
    words: 2500,
    createdOn: "----",
    category: "Scheduled Articles",
  },
  {
    title: "Creating an Efficient Workflow for Designers",
    keyword: "designer workflow",
    traffic: "3200",
    words: 2300,
    createdOn: "----",
    category: "Scheduled Articles",
  },
  {
    title: "Guide to Influencer Outreach",
    keyword: "influencer marketing",
    traffic: "3500",
    words: 2400,
    createdOn: "----",
    category: "Scheduled Articles",
  },
  {
    title: "The Ultimate Guide to B2B Content Strategy",
    keyword: "b2b content",
    traffic: "2700",
    words: 2200,
    createdOn: "4 days ago",
    category: "Scheduled Articles",
  },
  {
    title: "Launching a Newsletter That Converts",
    keyword: "email newsletter tips",
    traffic: "1900",
    words: 2100,
    createdOn: "5 days ago",
    category: "Scheduled Articles",
  },
  {
    title: "Common Landing Page Mistakes to Avoid",
    keyword: "landing page mistakes",
    traffic: "2600",
    words: 2000,
    createdOn: "6 days ago",
    category: "Scheduled Articles",
  },

  // --- Archived Articles (10) ---
  {
    title: "Top Virtual Executive Assistant Services (2024)",
    keyword: "virtual executive assistant",
    traffic: "2900",
    words: 2408,
    createdOn: "1 Oct, 24",
    category: "Archived Articles",
  },
  {
    title: "How to Prepare for Remote Interviews",
    keyword: "remote job interview tips",
    traffic: "3200",
    words: 2600,
    createdOn: "2 weeks ago",
    category: "Archived Articles",
  },
  {
    title: "Why Companies Are Hiring Virtual CFOs",
    keyword: "virtual cfo",
    traffic: "1500",
    words: 2250,
    createdOn: "2 weeks ago",
    category: "Archived Articles",
  },
  {
    title: "Top Outsourced Services for Startups",
    keyword: "startup outsourcing",
    traffic: "1800",
    words: 1950,
    createdOn: "3 weeks ago",
    category: "Archived Articles",
  },
  {
    title: "Remote Team Management Tools You Should Know",
    keyword: "remote tools",
    traffic: "2750",
    words: 2100,
    createdOn: "----",
    category: "Archived Articles",
  },
  {
    title: "Advantages of Hiring Virtual Assistants",
    keyword: "hire virtual assistant",
    traffic: "3400",
    words: 2350,
    createdOn: "----",
    category: "Archived Articles",
  },
  {
    title: "Building a Remote Work Culture",
    keyword: "remote work culture",
    traffic: "2100",
    words: 2200,
    createdOn: "3 weeks ago",
    category: "Archived Articles",
  },
  {
    title: "How to Transition from Onsite to Remote",
    keyword: "onsite to remote",
    traffic: "1700",
    words: 2400,
    createdOn: "4 weeks ago",
    category: "Archived Articles",
  },
  {
    title: "Managing Time Zones in Global Teams",
    keyword: "timezone management",
    traffic: "1850",
    words: 1900,
    createdOn: "5 weeks ago",
    category: "Archived Articles",
  },
  {
    title: "Tools for Asynchronous Communication",
    keyword: "async communication tools",
    traffic: "2300",
    words: 2500,
    createdOn: "6 weeks ago",
    category: "Archived Articles",
  },
];
